Repository Emmanuel-Melon/la-revue, pull requests merged in 2019-11, with the labels that each got.

#1 basic client set up
  client/.gitignore
  client/README.md
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/Utils/api.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/serviceWorker.js
  client/yarn.lock
Labels: enhancement

#4 added map and some dummy data
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/Components/Filter.js
  client/src/Components/ListRestaurants.js
  client/src/Components/Map.js
  client/src/Components/Navbar.js
  client/src/Components/RestaurantDetail.js
  client/src/Components/RestaurantSummary.js
  client/src/Components/data.json
  client/src/Services/Geolocation.js
  client/src/Services/Places.js
  client/src/Utils/api.js
  client/src/index.js
  client/src/serviceWorker.js
Labels: enhancement

#5 Ft da os
  server/reviews/DAOs/Reviews.DAO.js
  server/server.js
  server/services/mongodb.js
  server/utils/crud.js
Labels: enhancement

#6 added review controllers
  server/reviews/DAOs/Reviews.DAO.js
  server/reviews/controllers/addReview.controller.js
  server/reviews/controllers/getReview.controller.js
  server/reviews/controllers/getReviews.controller.js
  server/reviews/controllers/removeReview.controller.js
  server/reviews/routes.js
Labels: enhancement

#7 added basic structure for managing restaurants
  client/src/App.css
  client/src/App.js
  client/src/Components/Filter.js
  client/src/Components/RestaurantSummary.js
  client/src/Components/Search.js
  server/restaurants/DAOs/Restaurants.DAO.js
  server/restaurants/controllers/addRestaurant.controller.js
  server/restaurants/controllers/getRestauarants.controller.js
  server/restaurants/controllers/getRestaurant.controller.js
  server/restaurants/routes.js
Labels: enhancement

#8 Ft ui redesign
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/Components/Filter.js
  client/src/Components/Map.js
  client/src/Components/Navbar.js
  client/src/Components/Ratings.js
  client/src/Components/RestaurantSummary.js
  client/src/Components/Search.js
  client/yarn.lock
Labels: enhancement

#10 created expandable filter component
  client/package.json
  client/src/App.css
  client/src/Components/Expandable.js
  client/src/Components/Filter.js
  client/src/Components/Map.js
  client/src/Components/Navbar.js
  client/src/Components/Ratings.js
  client/src/Components/RestaurantSummary.js
  client/src/Components/Search.js
  client/src/Screens/Home.js
  client/yarn.lock
Labels: enhancement

#14 Ft pages #2
  client/src/App.css
  client/src/App.js
  client/src/Components/ListRestaurants.js
  client/src/Components/Navbar.js
  client/src/Screens/About.js
  client/src/Screens/Home.js
  package.json
  server/restaurants/tests/integration/restaurant.test.js
  server/restaurants/tests/unit/restaurant.test.js
  server/server.js
  yarn.lock
Labels: enhancement

#13 Move API KEY to environment variable
  client/src/Components/Map.js
Labels: ready, security_concern

#15 moved Google API keys into an .env file
  .gitignore
  client/.gitignore
  client/src/Components/Map.js
  package.json
  server/restaurants/controllers/getRestauarants.controller.js
  server/restaurants/routes.js
  server/server.js
  yarn.lock
Labels: enhancement, ready

#16 moved mongodb connection info into .env files
  server/restaurants/routes.js
  server/services/mongodb.js
Labels: enhancement, ready, security_concern

#17 fixed restaurants screen layout
  client/src/App.css
  client/src/Screens/Restaurants.js
Labels: enhancement, ready

#18 refactored css code into styled-components
  client/src/App.css
  client/src/Components/CustomButton.js
  client/src/Components/CustomImage.js
  client/src/Components/Map.js
  client/src/Components/Navbar.js
  client/src/Components/RestaurantSummary.js
  client/src/Components/Search.js
  client/src/Screens/About.js
  client/src/Screens/Home.js
  client/src/Screens/Restaurants.js
Labels: enhancement, ready

#19 refactored to functinal components
  client/src/Screens/About.js
  client/src/Screens/Home.js
  client/src/Screens/Restaurants.js
  client/src/Screens/fine.svg
  client/src/Utils/api.js
Labels: enhancement, ready

#20 persist restaurants into MongoDB
  .gitignore
  server/restaurants/DAOs/Restaurants.DAO.js
  server/restaurants/controllers/getRestauarants.controller.js
  server/utils/crud.js
Labels: enhancement, ready

#21 Ft added context
  client/src/App.css
  client/src/App.js
  client/src/Components/AddRestaurant.js
  client/src/Components/ListRestaurants.js
  client/src/Components/Map.js
  client/src/Components/RestaurantInfo.js
  client/src/Components/RestaurantSummary.js
  client/src/Components/ReviewSummary.js
  client/src/Screens/Home.js
  client/src/Screens/Restaurants.js
  client/src/Utils/api.js
  client/src/index.css
  server/restaurants/controllers/addRestaurant.controller.js
  server/restaurants/controllers/getRestauarants.controller.js
  server/restaurants/routes.js
  server/utils/crud.js
Labels: enhancement
